In [160]:
import pandas as pd
import numpy as np


from sklearn.linear_model import Perceptron
from lib_adult import accuracy
from lib_adult import metric
from lib_adult.resample import split_stratified_train_test 

from lib_adult import transform
from importlib import reload
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
 
#"error", "ignore", "always", "default", "module" or "once"

In [161]:
reload(resample)
reload(transform)

# Carregamento dos dados

In [162]:
columns = ['Age','Workclass', 'Fnlwgt', 'Education', 'Education-num', 'Marital-status',
           'Occupation','Relationship', 'Race', 'Sex', 
           'Capital-gain', 'Capital-loss', 'Hours-per-week','Native-country', 'Label']
original_data = pd.read_csv('adult.data', na_values='?', sep= ',\s+', names=columns, engine='python')

# Pre-processamento

In [163]:
original_data = original_data.drop(['Education'], axis=1)
# Indentificação das colunas com dados categóricos
cat_columns  = original_data.select_dtypes(['object']).columns
#'Object' é sobre as colunas categóricas

In [164]:
original_data.head()

,Age,Workclass,Fnlwgt,Education-num,Marital-status,Occupation,Relationship,Race,Sex,Capital-gain,Capital-loss,Hours-per-week,Native-country,Label
0,39,State-gov,77516,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [165]:
original_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 14 columns):
Age               32561 non-null int64
Workclass         30725 non-null object
Fnlwgt            32561 non-null int64
Education-num     32561 non-null int64
Marital-status    32561 non-null object
Occupation        30718 non-null object
Relationship      32561 non-null object
Race              32561 non-null object
Sex               32561 non-null object
Capital-gain      32561 non-null int64
Capital-loss      32561 non-null int64
Hours-per-week    32561 non-null int64
Native-country    31978 non-null object
Label             32561 non-null object
dtypes: int64(6), object(8)
memory usage: 3.5+ MB

In [166]:
original_data.isna().sum()

Age                  0
Workclass         1836
Fnlwgt               0
Education-num        0
Marital-status       0
Occupation        1843
Relationship         0
Race                 0
Sex                  0
Capital-gain         0
Capital-loss         0
Hours-per-week       0
Native-country     583
Label                0
dtype: int64

In [167]:
# Tratamento de colunas com missing values. Substituição pela moda (apenas colunas categóricas)
#for column in columns:
#    if ' ?' in original_data[column].unique():
#        
#        original_data[column] = original_data[column].replace(' ?',original_data[column].mode()[0])
#[0] está pegando os valores

In [168]:
for column in ['Workclass', 'Occupation', 'Native-country']:
    original_data[column] = original_data[column].replace(np.nan, original_data[column].mode()[0])

In [169]:
original_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 14 columns):
Age               32561 non-null int64
Workclass         32561 non-null object
Fnlwgt            32561 non-null int64
Education-num     32561 non-null int64
Marital-status    32561 non-null object
Occupation        32561 non-null object
Relationship      32561 non-null object
Race              32561 non-null object
Sex               32561 non-null object
Capital-gain      32561 non-null int64
Capital-loss      32561 non-null int64
Hours-per-week    32561 non-null int64
Native-country    32561 non-null object
Label             32561 non-null object
dtypes: int64(6), object(8)
memory usage: 3.5+ MB

In [170]:
# Transformar categóricos em one-hot encoding
original_data = pd.get_dummies(original_data, columns=cat_columns, prefix=cat_columns, drop_first=True)
original_data = original_data.rename(columns={'Label_>50K':'Label'})

In [171]:
original_data.head()

,Age,Fnlwgt,Education-num,Capital-gain,Capital-loss,Hours-per-week,Workclass_Local-gov,Workclass_Never-worked,Workclass_Private,Workclass_Self-emp-inc,...,Native-country_Puerto-Rico,Native-country_Scotland,Native-country_South,Native-country_Taiwan,Native-country_Thailand,Native-country_Trinadad&Tobago,Native-country_United-States,Native-country_Vietnam,Native-country_Yugoslavia,Label
0,39,77516,13,2174,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,50,83311,13,0,0,13,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,38,215646,9,0,0,40,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
3,53,234721,7,0,0,40,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
4,28,338409,13,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [172]:
original_data.columns

Index(['Age', 'Fnlwgt', 'Education-num', 'Capital-gain', 'Capital-loss',
       'Hours-per-week', 'Workclass_Local-gov', 'Workclass_Never-worked',
       'Workclass_Private', 'Workclass_Self-emp-inc',
       'Workclass_Self-emp-not-inc', 'Workclass_State-gov',
       'Workclass_Without-pay', 'Marital-status_Married-AF-spouse',
       'Marital-status_Married-civ-spouse',
       'Marital-status_Married-spouse-absent', 'Marital-status_Never-married',
       'Marital-status_Separated', 'Marital-status_Widowed',
       'Occupation_Armed-Forces', 'Occupation_Craft-repair',
       'Occupation_Exec-managerial', 'Occupation_Farming-fishing',
       'Occupation_Handlers-cleaners', 'Occupation_Machine-op-inspct',
       'Occupation_Other-service', 'Occupation_Priv-house-serv',
       'Occupation_Prof-specialty', 'Occupation_Protective-serv',
       'Occupation_Sales', 'Occupation_Tech-support',
       'Occupation_Transport-moving', 'Relationship_Not-in-family',
       'Relationship_Other-relative', 'Relationship_Own-child',
       'Relationship_Unmarried', 'Relationship_Wife',
       'Race_Asian-Pac-Islander', 'Race_Black', 'Race_Other', 'Race_White',
       'Sex_Male', 'Native-country_Canada', 'Native-country_China',
       'Native-country_Columbia', 'Native-country_Cuba',
       'Native-country_Dominican-Republic', 'Native-country_Ecuador',
       'Native-country_El-Salvador', 'Native-country_England',
       'Native-country_France', 'Native-country_Germany',
       'Native-country_Greece', 'Native-country_Guatemala',
       'Native-country_Haiti', 'Native-country_Holand-Netherlands',
       'Native-country_Honduras', 'Native-country_Hong',
       'Native-country_Hungary', 'Native-country_India', 'Native-country_Iran',
       'Native-country_Ireland', 'Native-country_Italy',
       'Native-country_Jamaica', 'Native-country_Japan', 'Native-country_Laos',
       'Native-country_Mexico', 'Native-country_Nicaragua',
       'Native-country_Outlying-US(Guam-USVI-etc)', 'Native-country_Peru',
       'Native-country_Philippines', 'Native-country_Poland',
       'Native-country_Portugal', 'Native-country_Puerto-Rico',
       'Native-country_Scotland', 'Native-country_South',
       'Native-country_Taiwan', 'Native-country_Thailand',
       'Native-country_Trinadad&Tobago', 'Native-country_United-States',
       'Native-country_Vietnam', 'Native-country_Yugoslavia', 'Label'],
      dtype='object')

# Separação

##### Features e Labels

In [173]:
X = original_data.drop(['Label'], axis=1)
y = original_data[['Label']]

##### Dados de treino e teste

In [175]:
perc_train          = 0.7
seed                = 42
#idx: índices que retornam na função de split_stratified_train_test no módulo

idx_train, idx_test = split_stratified_train_test(y, perc_train, seed)

In [177]:
#.loc: Acessar um grupo de linhas e colunas por labels ou uma matriz booleana.
X_train = X.loc[idx_train]
X_test = X.loc[idx_test]

y_train = y.loc[idx_train]
y_test = y.loc[idx_test]

In [186]:
np.unique(y_train, return_counts=True)

(array([0, 1], dtype=uint8), array([17329,  5464], dtype=int64))

In [188]:
17329/(17329+5464), 5464/(17329+5464)

(0.760277278111701, 0.23972272188829905)

In [190]:
np.unique(y_test, return_counts=True)

(array([0, 1], dtype=uint8), array([7390, 2377], dtype=int64))

In [192]:
7390/(7390+2377), 2377/(7390+2377)

(0.7566294665711067, 0.2433705334288932)

In [193]:
np.unique(y, return_counts=True)

(array([0, 1], dtype=uint8), array([24720,  7841], dtype=int64))

In [195]:
24720/(24720+7841), 7841/(24720+7841)

(0.7591904425539756, 0.2408095574460244)

In [196]:
X_train

,Age,Fnlwgt,Education-num,Capital-gain,Capital-loss,Hours-per-week,Workclass_Local-gov,Workclass_Never-worked,Workclass_Private,Workclass_Self-emp-inc,...,Native-country_Portugal,Native-country_Puerto-Rico,Native-country_Scotland,Native-country_South,Native-country_Taiwan,Native-country_Thailand,Native-country_Trinadad&Tobago,Native-country_United-States,Native-country_Vietnam,Native-country_Yugoslavia
14160,27,160178,10,0,0,38,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
27048,45,50567,9,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
28868,29,185908,13,0,0,55,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
5667,30,190040,13,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
7827,29,189346,10,2202,0,50,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
15382,51,108435,14,0,0,47,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
4641,58,93664,9,15024,0,60,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
8943,22,148431,9,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
216,50,313321,12,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
5121,50,71417,9,3103,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
345,43,241895,13,0,0,42,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
31900,37,271013,9,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
20010,41,152529,13,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
11808,46,116952,4,0,0,45,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
14587,33,226629,10,0,0,35,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
10021,45,161819,7,0,0,25,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
8966,43,99212,11,3103,0,48,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
1912,52,179951,15,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
2874,38,115433,12,7688,0,33,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
28771,32,267161,13,0,0,30,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
13061,40,439919,5,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4457,31,93589,9,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
29623,51,95329,14,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
11791,23,227594,9,0,0,30,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
31706,29,50295,10,0,0,48,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
16561,32,159187,13,0,0,35,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
26084,59,167963,9,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
29613,32,237903,13,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
5018,33,129707,10,0,0,50,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
31237,18,231562,9,0,0,33,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21035,25,221757,9,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
5677,32,249550,10,0,0,44,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
947,36,108293,13,0,1977,45,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
24502,45,44791,13,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
2147,58,187487,9,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
8788,18,276864,10,0,1602,20,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
19089,58,30111,10,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
7129,36,112497,13,0,1876,44,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
25113,23,69911,1,0,0,15,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
27838,56,119069,13,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
9699,28,109162,14,0,0,50,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
26800,27,119793,10,0,0,55,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
10955,43,396116,9,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
6841,35,140854,9,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
17194,23,49296,9,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
21701,26,391349,13,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
31421,42,175935,9,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
16696,44,115932,14,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2073,51,133050,10,0,0,40,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
9730,48,254291,13,7298,0,50,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
28287,43,52498,13,0,0,50,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
27919,41,191814,9,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
7734,21,70261,10,0,0,30,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
885,63,149698,10,0,0,15,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
18174,30,47085,6,0,0,40,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
11334,59,188070,14,0,0,35,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
14621,23,157127,10,0,0,20,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
15332,29,109814,13,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
7329,33,132832,9,0,0,50,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
10200,34,152667,10,0,0,35,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0

# Normalização dos Dados

In [203]:
X_train.max()

Age                                               90
Fnlwgt                                       1484705
Education-num                                     16
Capital-gain                                   99999
Capital-loss                                    4356
Hours-per-week                                    99
Workclass_Local-gov                                1
Workclass_Never-worked                             1
Workclass_Private                                  1
Workclass_Self-emp-inc                             1
Workclass_Self-emp-not-inc                         1
Workclass_State-gov                                1
Workclass_Without-pay                              1
Marital-status_Married-AF-spouse                   1
Marital-status_Married-civ-spouse                  1
Marital-status_Married-spouse-absent               1
Marital-status_Never-married                       1
Marital-status_Separated                           1
Marital-status_Widowed                             1
Occupation_Armed-Forces                            1
Occupation_Craft-repair                            1
Occupation_Exec-managerial                         1
Occupation_Farming-fishing                         1
Occupation_Handlers-cleaners                       1
Occupation_Machine-op-inspct                       1
Occupation_Other-service                           1
Occupation_Priv-house-serv                         1
Occupation_Prof-specialty                          1
Occupation_Protective-serv                         1
Occupation_Sales                                   1
                                              ...
Native-country_Greece                              1
Native-country_Guatemala                           1
Native-country_Haiti                               1
Native-country_Holand-Netherlands                  1
Native-country_Honduras                            1
Native-country_Hong                                1
Native-country_Hungary                             1
Native-country_India                               1
Native-country_Iran                                1
Native-country_Ireland                             1
Native-country_Italy                               1
Native-country_Jamaica                             1
Native-country_Japan                               1
Native-country_Laos                                1
Native-country_Mexico                              1
Native-country_Nicaragua                           1
Native-country_Outlying-US(Guam-USVI-etc)          1
Native-country_Peru                                1
Native-country_Philippines                         1
Native-country_Poland                              1
Native-country_Portugal                            1
Native-country_Puerto-Rico                         1
Native-country_Scotland                            1
Native-country_South                               1
Native-country_Taiwan                              1
Native-country_Thailand                            1
Native-country_Trinadad&Tobago                     1
Native-country_United-States                       1
Native-country_Vietnam                             1
Native-country_Yugoslavia                          1
Length: 82, dtype: int64

In [205]:
X_train.min()

Age                                             17
Fnlwgt                                       12285
Education-num                                    1
Capital-gain                                     0
Capital-loss                                     0
Hours-per-week                                   1
Workclass_Local-gov                              0
Workclass_Never-worked                           0
Workclass_Private                                0
Workclass_Self-emp-inc                           0
Workclass_Self-emp-not-inc                       0
Workclass_State-gov                              0
Workclass_Without-pay                            0
Marital-status_Married-AF-spouse                 0
Marital-status_Married-civ-spouse                0
Marital-status_Married-spouse-absent             0
Marital-status_Never-married                     0
Marital-status_Separated                         0
Marital-status_Widowed                           0
Occupation_Armed-Forces                          0
Occupation_Craft-repair                          0
Occupation_Exec-managerial                       0
Occupation_Farming-fishing                       0
Occupation_Handlers-cleaners                     0
Occupation_Machine-op-inspct                     0
Occupation_Other-service                         0
Occupation_Priv-house-serv                       0
Occupation_Prof-specialty                        0
Occupation_Protective-serv                       0
Occupation_Sales                                 0
                                             ...
Native-country_Greece                            0
Native-country_Guatemala                         0
Native-country_Haiti                             0
Native-country_Holand-Netherlands                0
Native-country_Honduras                          0
Native-country_Hong                              0
Native-country_Hungary                           0
Native-country_India                             0
Native-country_Iran                              0
Native-country_Ireland                           0
Native-country_Italy                             0
Native-country_Jamaica                           0
Native-country_Japan                             0
Native-country_Laos                              0
Native-country_Mexico                            0
Native-country_Nicaragua                         0
Native-country_Outlying-US(Guam-USVI-etc)        0
Native-country_Peru                              0
Native-country_Philippines                       0
Native-country_Poland                            0
Native-country_Portugal                          0
Native-country_Puerto-Rico                       0
Native-country_Scotland                          0
Native-country_South                             0
Native-country_Taiwan                            0
Native-country_Thailand                          0
Native-country_Trinadad&Tobago                   0
Native-country_United-States                     0
Native-country_Vietnam                           0
Native-country_Yugoslavia                        0
Length: 82, dtype: int64

In [210]:
X_train.mean()

Age                                              38.598385
Fnlwgt                                       189515.925416
Education-num                                    10.061028
Capital-gain                                   1068.373097
Capital-loss                                     83.259597
Hours-per-week                                   40.399026
Workclass_Local-gov                               0.064274
Workclass_Never-worked                            0.000175
Workclass_Private                                 0.755583
Workclass_Self-emp-inc                            0.034440
Workclass_Self-emp-not-inc                        0.076164
Workclass_State-gov                               0.039530
Workclass_Without-pay                             0.000483
Marital-status_Married-AF-spouse                  0.000614
Marital-status_Married-civ-spouse                 0.459176
Marital-status_Married-spouse-absent              0.013250
Marital-status_Never-married                      0.326942
Marital-status_Separated                          0.032993
Marital-status_Widowed                            0.031062
Occupation_Armed-Forces                           0.000263
Occupation_Craft-repair                           0.125565
Occupation_Exec-managerial                        0.123196
Occupation_Farming-fishing                        0.030580
Occupation_Handlers-cleaners                      0.043566
Occupation_Machine-op-inspct                      0.061028
Occupation_Other-service                          0.100601
Occupation_Priv-house-serv                        0.004738
Occupation_Prof-specialty                         0.183697
Occupation_Protective-serv                        0.020796
Occupation_Sales                                  0.111174
                                                 ...
Native-country_Greece                             0.000614
Native-country_Guatemala                          0.001843
Native-country_Haiti                              0.001272
Native-country_Holand-Netherlands                 0.000044
Native-country_Honduras                           0.000483
Native-country_Hong                               0.000658
Native-country_Hungary                            0.000395
Native-country_India                              0.003159
Native-country_Iran                               0.001228
Native-country_Ireland                            0.000526
Native-country_Italy                              0.002281
Native-country_Jamaica                            0.002545
Native-country_Japan                              0.001843
Native-country_Laos                               0.000483
Native-country_Mexico                             0.020006
Native-country_Nicaragua                          0.001009
Native-country_Outlying-US(Guam-USVI-etc)         0.000351
Native-country_Peru                               0.001097
Native-country_Philippines                        0.006098
Native-country_Poland                             0.001667
Native-country_Portugal                           0.001185
Native-country_Puerto-Rico                        0.003510
Native-country_Scotland                           0.000483
Native-country_South                              0.002281
Native-country_Taiwan                             0.001755
Native-country_Thailand                           0.000526
Native-country_Trinadad&Tobago                    0.000702
Native-country_United-States                      0.914360
Native-country_Vietnam                            0.001974
Native-country_Yugoslavia                         0.000395
Length: 82, dtype: float64

In [202]:
(X_train - X_train.min())/ (X_train.max() - X_train.min())

,Age,Fnlwgt,Education-num,Capital-gain,Capital-loss,Hours-per-week,Workclass_Local-gov,Workclass_Never-worked,Workclass_Private,Workclass_Self-emp-inc,...,Native-country_Portugal,Native-country_Puerto-Rico,Native-country_Scotland,Native-country_South,Native-country_Taiwan,Native-country_Thailand,Native-country_Trinadad&Tobago,Native-country_United-States,Native-country_Vietnam,Native-country_Yugoslavia
14160,0.136986,0.100442,0.600000,0.000000,0.000000,0.377551,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
27048,0.383562,0.025999,0.533333,0.000000,0.000000,0.397959,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
28868,0.164384,0.117917,0.800000,0.000000,0.000000,0.551020,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5667,0.178082,0.120723,0.800000,0.000000,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
7827,0.164384,0.120252,0.600000,0.022020,0.000000,0.500000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
15382,0.465753,0.065301,0.866667,0.000000,0.000000,0.469388,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4641,0.561644,0.055269,0.533333,0.150242,0.000000,0.602041,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8943,0.068493,0.092464,0.533333,0.000000,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
216,0.452055,0.204450,0.733333,0.000000,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5121,0.452055,0.040160,0.533333,0.031030,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
345,0.356164,0.155941,0.800000,0.000000,0.000000,0.418367,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
31900,0.273973,0.175716,0.533333,0.000000,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
20010,0.328767,0.095247,0.800000,0.000000,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
11808,0.397260,0.071085,0.200000,0.000000,0.000000,0.448980,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
14587,0.219178,0.145573,0.600000,0.000000,0.000000,0.346939,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
10021,0.383562,0.101557,0.400000,0.000000,0.000000,0.244898,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8966,0.356164,0.059037,0.666667,0.031030,0.000000,0.479592,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1912,0.479452,0.113871,0.933333,0.000000,0.000000,0.397959,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2874,0.287671,0.070053,0.733333,0.076881,0.000000,0.326531,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
28771,0.205479,0.173100,0.800000,0.000000,0.000000,0.295918,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
13061,0.315068,0.290429,0.266667,0.000000,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4457,0.191781,0.055218,0.533333,0.000000,0.000000,0.397959,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
29623,0.465753,0.056400,0.866667,0.000000,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
11791,0.082192,0.146228,0.533333,0.000000,0.000000,0.295918,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
31706,0.164384,0.025815,0.600000,0.000000,0.000000,0.479592,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
16561,0.205479,0.099769,0.800000,0.000000,0.000000,0.346939,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
26084,0.575342,0.105729,0.533333,0.000000,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
29613,0.205479,0.153229,0.800000,0.000000,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5018,0.219178,0.079748,0.600000,0.000000,0.000000,0.500000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
31237,0.013699,0.148923,0.533333,0.000000,0.000000,0.326531,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21035,0.109589,0.142264,0.533333,0.000000,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5677,0.205479,0.161139,0.600000,0.000000,0.000000,0.438776,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
947,0.260274,0.065204,0.800000,0.000000,0.453857,0.448980,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
24502,0.383562,0.022077,0.800000,0.000000,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2147,0.561644,0.118989,0.533333,0.000000,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8788,0.013699,0.179690,0.600000,0.000000,0.367769,0.193878,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
19089,0.561644,0.012107,0.600000,0.000000,0.000000,0.397959,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
7129,0.260274,0.068059,0.800000,0.000000,0.430670,0.438776,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
25113,0.082192,0.039137,0.000000,0.000000,0.000000,0.142857,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
27838,0.534247,0.072523,0.800000,0.000000,0.000000,0.397959,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9699,0.150685,0.065794,0.866667,0.000000,0.000000,0.500000,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
26800,0.136986,0.073014,0.600000,0.000000,0.000000,0.551020,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
10955,0.356164,0.260680,0.533333,0.000000,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6841,0.246575,0.087318,0.533333,0.000000,0.000000,0.397959,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
17194,0.082192,0.025136,0.533333,0.000000,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
21701,0.123288,0.257443,0.800000,0.000000,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
31421,0.342466,0.111144,0.533333,0.000000,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
16696,0.369863,0.070392,0.866667,0.000000,0.000000,0.397959,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2073,0.465753,0.082018,0.600000,0.000000,0.000000,0.397959,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9730,0.424658,0.164359,0.800000,0.072981,0.000000,0.500000,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
28287,0.356164,0.027311,0.800000,0.000000,0.000000,0.500000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
27919,0.328767,0.121928,0.533333,0.000000,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
7734,0.054795,0.039375,0.600000,0.000000,0.000000,0.295918,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
885,0.630137,0.093325,0.600000,0.000000,0.000000,0.142857,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
18174,0.178082,0.023635,0.333333,0.000000,0.000000,0.397959,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
11334,0.575342,0.119385,0.866667,0.000000,0.000000,0.346939,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
14621,0.082192,0.098370,0.600000,0.000000,0.000000,0.193878,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
15332,0.164384,0.066237,0.800000,0.000000,0.000000,0.397959,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
7329,0.219178,0.081870,0.533333,0.000000,0.000000,0.500000,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
10200,0.232877,0.095341,0.600000,0.000000,0.000000,0.346939,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [199]:
transformer = transform.Normalize()
transformer.fit(X_train)

X_train_normalized = transformer.transform(X_train)
X_test_normalized = transformer.transform(X_test)

# Método de Classificação

##### Perceptron

In [243]:
# Utilizando o Perceptron
clf = Perceptron()
clf.fit(X_train_normalized, y_train)
y_pred = clf.predict(X_test_normalized)
acc_perceptron = accuracy(y_test, y_pred)
acc_perceptron

C:\Users\s_raf\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
C:\Users\s_raf\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.8245111088358759

In [245]:
# Utilizando o Perceptron
clf = Perceptron()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
acc_perceptron = accuracy(y_test, y_pred)
acc_perceptron

C:\Users\s_raf\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
C:\Users\s_raf\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.7772089689771681

#### KNN

In [249]:
knn = KNeighborsClassifier()
knn.fit(X_train_normalized, y_train)
y_pred = knn.predict(X_test_normalized)
acc_knn = accuracy(y_test, y_pred)
acc_knn

C:\Users\s_raf\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

0.8248182655882051

##### Decision Tree

In [250]:
dt = DecisionTreeClassifier()
dt.fit(X_train_normalized, y_train)
y_hat = knn.predict(X_test_normalized)
acc_dt = accuracy(y_test, y_hat)
acc_dt

0.8248182655882051