# <center> Lista 5

### Objetivo: realizar a predição para obter o preço de venda de um imóvel a partir do seguinte dataset "Boston House Price Dataset".

In [22]:
import numpy as np
import pandas as pd
import matplotlib as plt
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor
from ml_libs import Regressao_linear_gd
from ml_libs import metricas
from ml_libs import Normalizacao
from importlib import reload

In [23]:
reload(Regressao_linear_gd)
reload(metricas)

In [3]:
cols = ['CRIM ','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','MEDV']
df = pd.read_csv('housing.csv',names=cols, sep='\s+')

In [4]:
df.head(5)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

### Informações sobre Atributos:

    01. CRIM    Taxa de criminalidade per capita por cidade
    02. ZN      proporção de terrenos residenciais zoneada para lotes mais 25.000 pés quadrados
    03. INDUS   proporção de hectares comerciais não varejistas por cidade
    04. CHAS    Variável dummy Charles River (= 1 se limites do setor rio; 0 caso contrário)
    05. NOX     Concentração de óxidos nítricos (partes por 10 milhões)
    06. RM      média de quartos por habitação
    07. AGE     Proporção de unidades ocupadas pelo proprietário construídas antes de 1940
    08. DIS     Distâncias ponderadas pelo para cinco centros de emprego em Boston
    09. RAD     Índice de acessibilidade a rodovias radiais
    10. TAX     TAXA DE IMPOSTO DE IMPOSIÇÃO DE VALOR TOTAL POR 10.000
    11. PTRATIO Proporção aluno-professor por cidade
    12. B       1000(Bk - 0,63)^2 onde Bk é a proporção de negros pela cidade
    13. LSTAT   % Status menor da população
    14. MEDV    Valor mediano de residências ocupadas pelo proprietário em US$1000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null int64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null int64
TAX        506 non-null float64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
MEDV       506 non-null float64
dtypes: float64(12), int64(2)
memory usage: 55.4 KB

In [6]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677082,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [7]:
df.hist(bins=20, figsize=(15,15));

In [8]:
df.corr().style.set_precision(4)

### Selecionando as features X e label y

In [9]:
X = df.values[:, :-1]
y = df.values[:, -1]

### Randomização dos dados usando semente (seed)

In [10]:
rs = np.random.RandomState(1)
shuffled_indices = rs.permutation(X.shape[0])
shuffled_indices

array([307, 343,  47,  67, 362, 132, 292,  31, 218,  90, 481, 344, 119,
        66, 312, 407, 376, 225, 201, 147, 315, 146, 314, 324,  65, 425,
        34, 345, 261, 389, 351, 245, 204, 447, 330, 494, 446,   4, 406,
       486, 329, 334, 223, 475, 478, 419, 162, 394, 165, 102, 473, 242,
         5, 168, 490,  62, 399, 311,  17, 233, 420,  85, 397, 430, 214,
       179, 232, 342, 294, 164, 326, 386, 366,  29, 107, 483, 370, 285,
       159, 291, 128, 117, 189, 435, 350, 298, 449, 325, 497, 135, 503,
       257, 491,   6, 427,  11, 501,  92, 224, 110, 426, 443,  42,  58,
       385,  78, 424, 160, 185, 101, 268, 173, 428, 306, 258, 192, 339,
        18,  40, 267, 328, 454,  41, 361, 289, 498, 293, 502, 172,  80,
        46, 318,  93, 392,  81, 304, 142, 456, 180, 380, 355, 139, 106,
       238, 290, 246, 320, 467,  95, 122, 260,  23,  13,  61, 377,  39,
       365, 272, 208, 236,  98, 364, 249, 421, 422, 286, 347, 378, 127,
        82, 463, 207,  27,  89, 469,  73, 187, 171, 161,  69, 221,  91,
       411, 197, 383, 125, 247, 273,  59, 120,  12, 455, 270, 375, 505,
       459, 157, 340, 186, 372, 442, 412, 213, 452, 346, 295,  88, 322,
       131, 124, 174, 461, 191,  14, 484, 250, 123, 138, 111,  51, 485,
       112,   9,  19,  16, 341,   0, 379, 105, 277, 450, 488, 300, 230,
       429,  70, 323, 256, 283,  38, 150, 438, 493, 163, 167, 274, 206,
       244, 188, 436, 476, 145, 275, 432, 403, 349, 433, 410, 305, 284,
       331, 175, 417, 363, 229, 409, 228, 100, 408,  53, 227, 474, 504,
       154, 251, 158, 271,  44, 487, 113, 400, 211, 108, 169,  79, 477,
        84,   8,  32,  99, 440, 416, 222,  28, 287, 374,  55, 480, 482,
       415,  48, 418, 358,  33,  35,  63, 404, 310, 234, 495,  45, 303,
       177, 219, 451, 296,  21, 248, 309, 199, 137,  24, 184, 205, 134,
       299, 116, 212, 457, 434, 441, 231, 217,  56, 466, 401, 373, 439,
       181,  97, 114, 278, 118, 382, 170, 437,  54, 176, 327, 194, 198,
       360, 472, 182, 414, 354, 103, 220, 130, 353, 338, 368,  60,  94,
       193, 140, 148, 202, 152, 337, 479,  10, 269,  96, 210, 240,  57,
       301, 388, 359,  36, 453,  20, 445, 332,  75, 200,  77, 263, 499,
       149, 444,   2,  52, 262, 253, 462, 259, 333, 369, 321, 183, 151,
       458, 302, 190,  74, 348, 243, 489,  87, 239, 143, 423, 266, 288,
       136, 166,  83, 496, 155, 356, 381, 279, 126, 195, 265, 465, 104,
       153, 282, 391, 226, 367,  25, 196,  64,  15, 297, 371, 109, 336,
       308,  26,  76,  43, 280,   3, 464,  49, 405, 387, 492,  30, 121,
       431, 115, 470, 216, 264, 209, 316, 384,   1, 313,  22, 317, 319,
         7, 500, 141,  86, 352, 241, 471, 215,  68,  50, 398, 413, 156,
       252, 395, 468, 402, 357, 254, 276, 178, 281, 390, 237,  71, 460,
       129, 144, 448, 335, 133, 203, 393, 255,  72, 396, 235,  37])

In [11]:
X = X[shuffled_indices]
y = y[shuffled_indices]

In [13]:
X[:1]

array([[4.9320e-02, 3.3000e+01, 2.1800e+00, 0.0000e+00, 4.7200e-01,
        6.8490e+00, 7.0300e+01, 3.1827e+00, 7.0000e+00, 2.2200e+02,
        1.8400e+01, 3.9690e+02, 7.5300e+00]])

In [14]:
y[:5]

array([28.2, 23.9, 16.6, 22. , 20.8])

### Selecionando 70% dos dados para treino e 30% para teste

In [15]:
n = int(np.count_nonzero(y) * 0.70)
X_train = X[:n]
y_train = y[:n]
X_test = X[n:]
y_test = y[n:]

### Criando modelo de Regressao Linerar com Gradiente descendente

In [24]:
model = Regressao_linear_gd.LinearRegressionGD();

In [25]:
model.fit(X_train,y_train);

In [30]:
y_predict = model.predict(X_test);
y_predict

array([-1.73671457e+102, -1.47948773e+102, -1.63634781e+102,
       -1.45415169e+102, -1.76420976e+102, -1.14965739e+102,
       -1.25253770e+102, -2.25584967e+102, -1.40095227e+102,
       -1.37626231e+102, -1.33368461e+102, -1.75037144e+102,
       -1.61532001e+102, -1.53123150e+102, -1.58712353e+102,
       -1.25846192e+102, -2.26656688e+102, -1.46808295e+102,
       -1.25156970e+102, -1.37576459e+102, -1.38997326e+102,
       -1.42606647e+102, -1.32542830e+102, -1.49594296e+102,
       -2.25320374e+102, -2.27734002e+102, -1.35417214e+102,
       -2.25732279e+102, -1.43116336e+102, -1.65095378e+102,
       -1.37092706e+102, -1.63229666e+102, -1.63554300e+102,
       -1.63945170e+102, -1.36099564e+102, -1.64975009e+102,
       -1.60593264e+102, -2.01071803e+102, -1.29609256e+102,
       -1.29217109e+102, -1.34763215e+102, -1.48797097e+102,
       -2.28932310e+102, -1.35999042e+102, -1.24098496e+102,
       -2.25443460e+102, -1.40498557e+102, -1.20334105e+102,
       -1.58857738e+102, -2.06300588e+102, -1.46572383e+102,
       -1.61468783e+102, -1.63907236e+102, -1.37237744e+102,
       -1.37847733e+102, -2.30220307e+102, -1.31043610e+102,
       -1.40775067e+102, -1.69009494e+102, -1.57352337e+102,
       -1.34058511e+102, -1.41793864e+102, -1.73196474e+102,
       -1.63700459e+102, -1.37803795e+102, -1.65199921e+102,
       -1.12121553e+102, -2.26003890e+102, -2.29592157e+102,
       -1.23378908e+102, -1.12638646e+102, -1.32116538e+102,
       -1.34737758e+102, -2.16279319e+102, -1.63398467e+102,
       -1.44337649e+102, -1.20407713e+102, -2.25573357e+102,
       -1.44515545e+102, -1.81279946e+102, -1.29327809e+102,
       -1.49678888e+102, -1.23747629e+102, -1.44967398e+102,
       -1.41156642e+102, -2.23937493e+102, -1.63199662e+102,
       -1.25731608e+102, -1.45425035e+102, -1.42844932e+102,
       -1.62593087e+102, -1.25857670e+102, -1.22818350e+102,
       -1.24754231e+102, -2.28283175e+102, -1.28399146e+102,
       -2.27587295e+102, -2.29324267e+102, -2.39217550e+102,
       -1.39998678e+102, -1.15471570e+102, -1.72007291e+102,
       -1.65686616e+102, -2.28979322e+102, -1.37336683e+102,
       -1.34964635e+102, -1.39989549e+102, -1.44415503e+102,
       -2.09170994e+102, -1.31035725e+102, -1.44818775e+102,
       -1.46564743e+102, -1.45103636e+102, -1.44487515e+102,
       -1.47660541e+102, -1.65404864e+102, -1.76945000e+102,
       -1.30797342e+102, -1.67122202e+102, -1.43620659e+102,
       -2.28916342e+102, -1.37188028e+102, -1.53275143e+102,
       -1.29931204e+102, -2.29738808e+102, -1.95831936e+102,
       -1.12655366e+102, -1.46767511e+102, -2.28642915e+102,
       -2.23418378e+102, -2.25824362e+102, -2.28203605e+102,
       -1.45714534e+102, -1.31491673e+102, -1.42231388e+102,
       -1.22713804e+102, -2.29016057e+102, -1.44467895e+102,
       -1.39687009e+102, -2.03439596e+102, -1.76642258e+102,
       -1.68943132e+102, -2.29542312e+102, -1.25287779e+102,
       -1.75152673e+102, -1.24866068e+102, -2.29295606e+102,
       -1.45674397e+102, -1.41841610e+102, -2.29443089e+102,
       -1.41710831e+102, -1.38186080e+102])

In [29]:
print(metricas.mse(y_test,y_predict))

2.7392669852412967e+204