In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("wdbc.data", header=-1)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

#### Removendo a primeira coluna que é o ID

In [3]:
df.drop(columns=[0], axis=1, inplace=True)
df.head()

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [4]:
df = pd.get_dummies(df, drop_first=True)

In [5]:
df.head()

,2,3,4,5,6,7,8,9,10,11,...,23,24,25,26,27,28,29,30,31,1_M
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,1
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,1
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,1
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,1
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,1

# Separando os dados

In [6]:
X = df.values[: , :-1]
y = df.values[:, -1]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)
# X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, test_size=.5, random_state=42)

In [9]:
X_train.shape, y_train.shape, X_test.shape,  y_test.shape #, X_val.shape,   y_val.shape

((455, 30), (455,), (114, 30), (114,))

# Grid Search

In [10]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [11]:
learning_rate = [0.1, 0.05, 0.01]
n_estimators = [50, 100, 200]
max_depth = [3, 5, 7]

pipe = {}
pipe['dt'] = Pipeline([('transformer', StandardScaler()),('dt', DecisionTreeClassifier())])
pipe['rf'] = Pipeline([('transformer', StandardScaler()),('rf', RandomForestClassifier())])
pipe['gb'] = Pipeline([('transformer', StandardScaler()),('gb', GradientBoostingClassifier())])

params = {}
params['dt'] = {'dt__max_depth': max_depth}
params['rf'] = {'rf__n_estimators': n_estimators, 'rf__max_depth': max_depth}
params['gb'] = {'gb__learning_rate': learning_rate, 'gb__n_estimators': n_estimators, 'gb__max_depth': max_depth}

cv = StratifiedKFold(n_splits=4, shuffle=True, random_state=42)
gs_result = {}
for key in pipe:
    gs = GridSearchCV(pipe[key], params[key], cv=cv, iid=True, scoring='accuracy', return_train_score=True)
    gs.fit(X_train, y_train)
    gs_result[key] = gs.cv_results_

# DecisionTreeClassifier

In [12]:
cols = ['params', 'mean_train_score', 'mean_test_score']
pd.DataFrame(gs_result['dt'])[cols].sort_values(by='mean_test_score', ascending=False)

                 params  mean_train_score  mean_test_score
0  {'dt__max_depth': 3}          0.979476         0.938462
1  {'dt__max_depth': 5}          0.991946         0.927473
2  {'dt__max_depth': 7}          0.999269         0.903297

In [13]:
dt = DecisionTreeClassifier(max_depth=5)
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)
accuracy_score(dt_pred, y_test)

0.9473684210526315

### Foi obtido uma melhor acurácia usando o dataset inteiro
## Importância das features

In [14]:
dt.feature_importances_ # muitas features têm importância 0

array([0.        , 0.03135535, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.70369564, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.01219532, 0.00125874,
       0.        , 0.0063872 , 0.01621366, 0.        , 0.0188839 ,
       0.05322784, 0.02816058, 0.05240823, 0.        , 0.00939712,
       0.        , 0.        , 0.06681641, 0.        , 0.        ])

# RandomForestClassifier

In [15]:
cols = ['params', 'mean_train_score', 'mean_test_score']
pd.DataFrame(gs_result['rf'])[cols].sort_values(by='mean_test_score', ascending=False)

,params,mean_train_score,mean_test_score
8,"{'rf__max_depth': 7, 'rf__n_estimators': 200}",0.999269,0.953846
3,"{'rf__max_depth': 5, 'rf__n_estimators': 50}",0.994137,0.951648
6,"{'rf__max_depth': 7, 'rf__n_estimators': 50}",0.998534,0.951648
4,"{'rf__max_depth': 5, 'rf__n_estimators': 100}",0.994141,0.949451
7,"{'rf__max_depth': 7, 'rf__n_estimators': 100}",0.999265,0.949451
5,"{'rf__max_depth': 5, 'rf__n_estimators': 200}",0.994141,0.947253
0,"{'rf__max_depth': 3, 'rf__n_estimators': 50}",0.986085,0.945055
1,"{'rf__max_depth': 3, 'rf__n_estimators': 100}",0.981678,0.945055
2,"{'rf__max_depth': 3, 'rf__n_estimators': 200}",0.982415,0.945055

In [16]:
rf = RandomForestClassifier(max_depth=7, n_estimators=100)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
accuracy_score(rf_pred, y_test)

0.9649122807017544

### Foi obtido uma melhor acurácia usando o dataset inteiro
## Importância das features

In [17]:
rf.feature_importances_ # Todos os atributos têm certa importância

array([0.05107474, 0.01234103, 0.04644149, 0.06056472, 0.00836039,
       0.00521031, 0.04500119, 0.10577523, 0.00389439, 0.00550817,
       0.0164778 , 0.00589906, 0.01563237, 0.01791771, 0.00480025,
       0.00380272, 0.01018299, 0.00392617, 0.00507067, 0.00557985,
       0.17406982, 0.01713492, 0.10462154, 0.03984874, 0.01227363,
       0.02497292, 0.03790024, 0.13492148, 0.01466385, 0.00613163])

# GradientBoosting

In [18]:
cols = ['params', 'mean_train_score', 'mean_test_score']
aux = pd.DataFrame(gs_result['gb'])[cols].sort_values(by='mean_test_score', ascending=False)
aux

,params,mean_train_score,mean_test_score
0,"{'gb__learning_rate': 0.1, 'gb__max_depth': 3,...",1.000000,0.953846
2,"{'gb__learning_rate': 0.1, 'gb__max_depth': 3,...",1.000000,0.953846
10,"{'gb__learning_rate': 0.05, 'gb__max_depth': 3...",1.000000,0.953846
11,"{'gb__learning_rate': 0.05, 'gb__max_depth': 3...",1.000000,0.951648
1,"{'gb__learning_rate': 0.1, 'gb__max_depth': 3,...",1.000000,0.951648
20,"{'gb__learning_rate': 0.01, 'gb__max_depth': 3...",0.994141,0.945055
9,"{'gb__learning_rate': 0.05, 'gb__max_depth': 3...",0.994141,0.942857
19,"{'gb__learning_rate': 0.01, 'gb__max_depth': 3...",0.991940,0.938462
17,"{'gb__learning_rate': 0.05, 'gb__max_depth': 7...",1.000000,0.936264
4,"{'gb__learning_rate': 0.1, 'gb__max_depth': 5,...",1.000000,0.936264
7,"{'gb__learning_rate': 0.1, 'gb__max_depth': 7,...",1.000000,0.936264
12,"{'gb__learning_rate': 0.05, 'gb__max_depth': 5...",1.000000,0.936264
23,"{'gb__learning_rate': 0.01, 'gb__max_depth': 5...",0.999265,0.934066
22,"{'gb__learning_rate': 0.01, 'gb__max_depth': 5...",0.997065,0.934066
8,"{'gb__learning_rate': 0.1, 'gb__max_depth': 7,...",1.000000,0.934066
13,"{'gb__learning_rate': 0.05, 'gb__max_depth': 5...",1.000000,0.931868
6,"{'gb__learning_rate': 0.1, 'gb__max_depth': 7,...",1.000000,0.931868
5,"{'gb__learning_rate': 0.1, 'gb__max_depth': 5,...",1.000000,0.931868
26,"{'gb__learning_rate': 0.01, 'gb__max_depth': 7...",1.000000,0.931868
14,"{'gb__learning_rate': 0.05, 'gb__max_depth': 5...",1.000000,0.929670
3,"{'gb__learning_rate': 0.1, 'gb__max_depth': 5,...",1.000000,0.929670
25,"{'gb__learning_rate': 0.01, 'gb__max_depth': 7...",1.000000,0.929670
16,"{'gb__learning_rate': 0.05, 'gb__max_depth': 7...",1.000000,0.927473
18,"{'gb__learning_rate': 0.01, 'gb__max_depth': 3...",0.980216,0.927473
21,"{'gb__learning_rate': 0.01, 'gb__max_depth': 5...",0.996334,0.925275
15,"{'gb__learning_rate': 0.05, 'gb__max_depth': 7...",1.000000,0.923077
24,"{'gb__learning_rate': 0.01, 'gb__max_depth': 7...",1.000000,0.923077

In [19]:
aux.values[0, 0] # só pra saber n_estimators

{'gb__learning_rate': 0.1, 'gb__max_depth': 3, 'gb__n_estimators': 50}

In [20]:
gb = GradientBoostingClassifier(learning_rate=.1, max_depth=7, n_estimators=100)
gb.fit(X_train, y_train)
gb_pred = gb.predict(X_test)
accuracy_score(gb_pred, y_test)

0.9385964912280702

### Não foi obtido uma melhor acurácia usando o dataset inteiro
## Importância das features

In [21]:
gb.feature_importances_ # todas os atributos têm certa importância

array([0.00000000e+00, 3.37114902e-02, 2.23762549e-08, 2.16153090e-08,
       5.73536797e-04, 2.24630592e-05, 1.51185942e-03, 6.92070598e-01,
       2.29135439e-03, 0.00000000e+00, 6.70290024e-03, 7.75415869e-04,
       2.56830601e-08, 5.27966620e-03, 1.42353617e-03, 7.79707217e-06,
       8.81638132e-03, 1.59307994e-02, 9.46842429e-04, 1.40402184e-02,
       5.22994182e-02, 3.49648873e-02, 5.14940763e-02, 1.31313048e-07,
       9.23318209e-03, 5.63149828e-04, 4.47872300e-06, 6.63203482e-02,
       1.01539973e-03, 0.00000000e+00])